[build]
builder          = "DOCKERFILE"
dockerfilePath   = "Dockerfile"

[build.args]
VITE_TLDRAW_LICENSE_KEY = "${{VITE_TLDRAW_LICENSE_KEY}}"
VITE_SERVER_URL         = "${{VITE_SERVER_URL}}"

[deploy]
startCommand     = "sh -c 'npm run db:migrate && npm run start'"
healthcheckPath    = "/health"
healthcheckTimeout = 120
restartPolicyType  = "ON_FAILURE"